apiVersion: v1
kind: Service
metadata:
  name: scalelink-analytics
  namespace: scalelink
  labels:
    app.kubernetes.io/name: scalelink-analytics
    app.kubernetes.io/component: analytics-service
    app.kubernetes.io/part-of: scalelink
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scalelink-analytics
    app.kubernetes.io/component: analytics-service
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
