apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalelink-link
  namespace: scalelink
  labels:
    app.kubernetes.io/name: scalelink-link
    app.kubernetes.io/component: link-service
    app.kubernetes.io/part-of: scalelink
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: scalelink-link
      app.kubernetes.io/component: link-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scalelink-link
        app.kubernetes.io/component: link-service
        app.kubernetes.io/part-of: scalelink
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: link
          image: veera491/scalelink-link:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: scalelink-secrets
                  key: DATABASE_URL
            - name: ANALYTICS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: scalelink-config
                  key: ANALYTICS_SERVICE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: scalelink-config
                  key: LOG_LEVEL
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
