apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scalelink-postgres-data
  namespace: scalelink
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: scalelink
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
